print()
print("* * * * *                *   *")
print("    *                   * * * *")
print("    *   Thomas         *   *   *")
print("    *       Monfre    *         *")
print("    *                *           *")

print()
print()
print()

print("* * * * *    *   *")
print("    *       * * * *")
print("    *      *   *   *")
print("    *     *         *")
print("    *    *           * Thomas Monfre")

print()
print()
print()

print("* * * * *    *   *")
print("    *       * * * *")
print("    *      *   *   *")
print("    *     *         *")
print("    *    *           *")
print()
print("      Thomas Monfre")

print()
print()
print()

print("* * * * *  *       *")
print("    *      * *   * *")
print("    *      *   *   *")
print("    *      *       *")
print("    *      *       *")
print()
print("     Thomas Monfre")

print()
print()
print()

print(" * * * * * * * * *")
print("     *   *   *")
print("    *  * * *  *")
print("   *     *     *")
print("  *      *      *")
print("         *")
print("   Thomas Monfre")

print()
print()
print()

print("* * * * *   *")
print("    * *   * *")
print("    *   *   *")
print("    *       *")
print("    *       *")
print()
print("      Thomas Monfre")

print()
print()
print()